### ISSUE TITLE
models.Datefield being localized where it shouldn't

### ISSUE THREAD

**Issue by akshaysalunke13** [django/code.djangoproject.com#102]
So, I have a DateField in my model and have also set I18N & L10N to `True`  in settings. When a browser running `en-AU` locale visits the website, Django tries to parse the value read from model, using the first value in `DATE_INPUT_FORMATS` from /conf.

The bug is when a user in `en-AU` locale visits the website, Django reads the Datefield value from model and tries to localize it for `en-AU` locale (from `DATE_INPUT_FORMATS` in /conf/en_AU) to this format `'%d/%m/%Y'`, but html5 requires the `value` for `<input type="date">` to be explicitly in this format: yyyy-MM-dd. [ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) [ref2](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#Format_of_a_valid_date_string).

This causes an error in chrome dev console and the HTML date field rendered without the date read from the model.
![image](https://user-images.githubusercontent.com/2255284/82113682-326dc080-979b-11ea-8e7f-c442f30aae1f.png)

![image](https://user-images.githubusercontent.com/2255284/82113676-2255e100-979b-11ea-973b-564fdb4a3497.png)

**This bug goes away when I disable L10N in settings. I am able to reproduce this bug in `en-AU` and `en-GB`**

**Comment by akshaysalunke13** [comment]
Sorry, I posted this in the wrong place. Where would a bug report for Django go?

**Comment by shaib** [comment]
Please see https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/

**Comment by akshaysalunke13** [comment]
> Please see https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/

Thanks for the reply @shaib. With a quick preliminary look, do you think this is a bug?

**Comment by shaib** [comment]
I can't rule it out without knowing more about how exactly you use the
model in generating the page. However, the place for such questions is
a support channel, see https://docs.djangoproject.com/en/3.0/faq/help/
