### ISSUE TITLE
The text input for "assign to" starts out pre-filled to an invalid value

### ISSUE THREAD

**Issue by cjerdonek** [django/code.djangoproject.com#114]
When creating a new issue, I noticed that the text input for the "assign to" field starts out prepopulated as `< default >`. I believe this should instead be the empty string with a placeholder value for display. This is a little confusing because it's not clear someone needs to delete the pre-filled value. In the past, I have tried submitting the default value as is, thinking it might mean self-assigning to me, but it resulted in being marked as assigned with noone getting assigned.

**Comment by bmispelon** [comment]
It took a bit of time, but better late than never, right? 😅 

The fix is deployed now, reopen if you still run into issues (I promise to look into it slightly faster than in 3 years).
