### ISSUE TITLE
Update name and logo for Django's Trac integration with GitHub.

### ISSUE THREAD

**Issue by ngnpope** [django/code.djangoproject.com#115]
I'm not sure if this is the place to report it, but thought I'd try here first...

I noticed on the *Authorized OAuth Apps* settings in GitHub that the Django Trac instance shows as **Trac**.

It would be nice if this were updated to **Django Trac** and had the Django logo to be more transparent like the forum app is.

This is what it currently looks like:

![github-oauth-apps](https://user-images.githubusercontent.com/2855582/128615891-626ccac3-5f3c-427f-a846-7aeb6dbec885.png)

**Comment by MarkusH** [comment]
Thanks for the report. I'll look into this.

**Comment by MarkusH** [comment]
Should be fixed, @ngnpope 

![image](https://user-images.githubusercontent.com/475613/128635894-ccba8696-f462-4fd4-90e7-fe748ba3b8b1.png)

**Comment by ngnpope** [comment]
Thanks @MarkusH. That looks great!
