### ISSUE TITLE
Unable to login through GitHub Login

### ISSUE THREAD

**Issue by claudep** [django/code.djangoproject.com#120]
From time to time, my login session on `code.djangoproject.com` expires, and normally clicking on GitHub Login is enough to login again. Today nothing happens when I click that link. Any known issue?

**Comment by charettes** [comment]
Same thing for me, wasn't able to login on either FF or Chrome.

**Comment by kezabelle** [comment]
Confirming the same problem here.
From the network console I can see:
- request to `https://code.djangoproject.com/github/login`
- redirect to `https://github.com/login/oauth/authorize?response_type=code[...]`
- redirect to `https://code.djangoproject.com/github/oauth?code=[...]`
- that last one redirects back to the landing page proper, having done `set-cookie: trac_auth=[...secret value...]`, expiring on the 26th of Feb.
- when the final page loads (`https://code.djangoproject.com/`) it includes `set-cookie: trac_auth=[BLANK]; expires=Sat, 12 Feb 2022 16:35:24 GMT [...]`

Notably the `trac_auth` which is I assume the relevant cookie is empty, and the expiry date is a few hours ago (I'm GMT, it's 19:30, not 16:30 ...)

**Comment by apollo13** [comment]
Seeing the same thing, that will be fun to fix I guess :)

**Comment by tobiasmcnulty** [comment]
Thanks for the reports + @apollo13 for the quick fix! As discussed on IRC I think we can leave the setting disabled (see: https://trac.edgewall.org/ticket/7664), but we will work to get the true client IP safely in a header where our apps can pick it up.

**Comment by claudep** [comment]
Thanks @apollo13, it works now.
