### ISSUE TITLE
Error creating users in tests

### ISSUE THREAD

**Issue by ArtTemiy** [django/code.djangoproject.com#125]
Hello,
I use this function in my setUp method of Tests classes to create users
But assertion always fails

```python
from django.contrib.auth.models import User


def create_account(username, password):
    user = User(username=username, password=password)
    user.save()
    assert User.objects.get(username=username).check_password(password)
```
However, if I explicitly call set_password after creating user, check will pass

```python
from django.contrib.auth.models import User


def create_account(username, password):
    user = User(username=username, password=password)
    user.set_password(password)  # !!!
    user.save()
    assert User.objects.get(username=username).check_password(password)
```

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
