### ISSUE TITLE
Django admin layout breaks when using help_text in 2 columns in admin

### ISSUE THREAD

**Issue by camarone** [django/code.djangoproject.com#135]
I'm using Django 4.2b1 and found a problem with the Django admin layout when I use the help_text in model admin. The help_text in the Admin form appears on a separate line and breaks the alignment of the fields. This happens in every browser I've tested.

Create a model with two or more fields that have help_text defined with a size larger than the field name. Register this model in admin.py with ModelAdmin and put them on the same line using fieldsets giving name to the line. Access the edit page of this model in Django admin and observe the layout.
Expected result:

The help_text should appear below the corresponding field, without affecting the alignment of the other fields.

**print with error on Django version 4.2b1**
![4 2b1](https://user-images.githubusercontent.com/1149071/222699976-7f8370ae-1ca2-4de0-8a6a-e7ea2be1f1f5.png)

**print without the error in Django version 4.1.5**
![4 1 7](https://user-images.githubusercontent.com/1149071/222699980-4ff5e213-16c2-4f72-b39f-264595cf3da8.png)

**Comment by claudep** [comment]
Thanks for reporting this issue! However you've find the wrong tracker, please report on https://code.djangoproject.com/

This tracker is for the code.djangoproject.com website itself.

**Comment by claudep** [comment]
(note for project admins, I don't have the rights to close tickets here)
