### ISSUE TITLE
Current guidelines for local setup broken due to Trac database_version update

### ISSUE THREAD

**Issue by sarahboyce** [django/code.djangoproject.com#141]
The sql for local setup was updated for prep of Trac 1.4: https://github.com/django/djangoproject.com/pull/1265
The README here has a dependency on this for local setup. 
```
    docker-compose exec -T db psql $DATABASE_URL < ../djangoproject.com/tracdb/trac.sql
```
The command: 
```
    docker-compose exec trac /venv/bin/trac-admin /code/trac-env/ permission add anonymous TRAC_ADMIN
```
Now fails with the error: `Error: Need to downgrade database_version.`

----

I assume this is just because the Trac version here is not yet 1.4 (though I see it is coming https://github.com/django/code.djangoproject.com/pull/133)

If anyone encounters the issue, if you check out the djangoproject.com repo prior to the change, run the commands, everything will just work.

As part of the 1.4 upgrade PR, we can test the local setup is still working :+1:

**Comment by bmispelon** [comment]
Should be fixed now that we're running Trac 1.4, thanks for the report 👍🏻
