### ISSUE TITLE
Trying to log out gives an error message

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#150]
Tried using either the Github login or the Djangoproject login. Once logged in, clicking the "Logout" button in the navigation gives the following error message (in red):

> Error: Bad Request
> Missing or invalid form token. Secure cookies are enabled, you must use https to submit forms.

(and the URL of the page is `https://code.djangoproject.com/github/logout`, even when logged in via Djangoproject and not github)

**Comment by cb109** [comment]
Can confirm. Use the GitHub Login then pressed the Logout link:

![Screenshot from 2024-01-25 13-56-24](https://github.com/django/code.djangoproject.com/assets/6052590/ea1478e4-493c-46df-9e61-4a042aec6102)

**Comment by bmispelon** [comment]
Still trying to get to the bottom of this, seems like it's related to https://github.com/trac-hacks/trac-github/issues/136
