### ISSUE TITLE
[styling] Too much whitespace between mainnav and content

### ISSUE THREAD

**Issue by smithdc1** [django/code.djangoproject.com#152]
For me, there is too much white space between the navbar and the content. It's somewhat noticeable on desktop, but is much more noticeable on narrower screen widths. For example:

![image](https://github.com/django/code.djangoproject.com/assets/39445562/04a0f23c-0a1a-4a14-a74b-f96ed1f07dda)

**Comment by sarahboyce** [comment]
I agree 😁 I think I tried to do this quite a while ago: https://github.com/django/code.djangoproject.com/pull/142

**Comment by bmispelon** [comment]
> I agree 😁 I think I tried to do this quite a while ago: #142

Your PR does a lot more than just fix this whitespace issue though (and I will get to reviewing it at some point, I promise 😁 ).

I wonder if an easy fix/win here would be to hide/remove the empty `<div id="ctxtnav">` that's in the top of all pages (and seems to only have visible elements on wiki pages), what do you think?

**Comment by sarahboyce** [comment]
> Also in general, no need to wait for a session. If you have questions or feedback, feel free to share at any point :green_heart: 

Yeah that's a good idea 👍

**Comment by felixxm** [comment]
Fixed.
