### ISSUE TITLE
[styling] Buttons have text-shadow. 

### ISSUE THREAD

**Issue by smithdc1** [django/code.djangoproject.com#153]
The buttons at the bottom of a ticket / create new ticket page have text-shadow. Is this intended? 

![image](https://github.com/django/code.djangoproject.com/assets/39445562/c2d37274-d228-4150-b472-57a6712c896a)

(I appreciate is a nit pic -- thank you again for all the efforts to upgrade trac!)

**Comment by bmispelon** [comment]
Trac loves shadows for some reason.

We have a script that reset all their `border-shadow`, I'll see if I can adapt it to also deal with `text-shadow`. Thanks for the report!
