### ISSUE TITLE
Shadow-looking background on comments

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#163]
There's a weird shadow-looking horizontal bar under comment titles on the ticket page:

![Screenshot 2024-01-25 at 22-09-49 #35141 (CACHE_MIDDLEWARE_SECONDS can be set to a float but has to be an int) – Django](https://github.com/django/code.djangoproject.com/assets/6345/4b90e59f-7a7c-449a-ab52-6c00ce3eb010)

It's not a `box-shadow` (that would have been caught by the `noshadows.py` script), this time it seems to be a fancy CSS background. Disabling the background completely looks a bit too empty, so I'm not sure how to replace it (maybe a simpler line rather than a gradient?).
We should also try to figure out if other elements are affected.

**Comment by felixxm** [comment]
Fixed.
