### ISSUE TITLE
Footer misses column-layout

### ISSUE THREAD

**Issue by apollo13** [django/code.djangoproject.com#165]
Scrolling down on https://code.djangoproject.com/ gives me:
![image](https://github.com/django/code.djangoproject.com/assets/81547/e730a74e-7a73-41bf-ac8a-03cb3c1a8a06)

whereas the normal homepage has:
![image](https://github.com/django/code.djangoproject.com/assets/81547/d6028edc-6d6a-4fd6-86e0-8bc64fdcd3e6)

/cc @bmispelon

**Comment by felixxm** [comment]
Fixed in #161.
