### ISSUE TITLE
Comment headers and changes overlap

### ISSUE THREAD

**Issue by smithdc1** [django/code.djangoproject.com#169]
Do you think there used to be a bit of whitespace between the comment headers and changes? It seems that there's a small overlap at the moment? 

![image](https://github.com/django/code.djangoproject.com/assets/39445562/a9ae59f0-e4ff-4835-8dd5-8ed7877ca03c)

It seems `trac-change-panel` currently has `margin-top: -.5em`. Removing this results in

![image](https://github.com/django/code.djangoproject.com/assets/39445562/8e62331f-a7b5-4ee7-af4a-35819a5236e2)

**Comment by bmispelon** [comment]
Thanks for the report, this does look weird. I can reproduce this locally when using a user that doesn't have the `TRAC_ADMIN` permission (otherwise a toolbar appears between the comment header and the header and adds some spacing).

I'll look into this.
