### ISSUE TITLE
Antispam flags links to github.com as malicious

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#179]
According to a [report on the forum](https://forum.djangoproject.com/t/potential-spam-error-trying-to-open-new-ticket/28149/2), the external service `dbl.spamhaus.org` is marking github.com as a spam site and the spam filter therefore rejects tickets/comments linking to PRs and such.

That's somewhat undesirable I would say 😅 

I've looked around a bit and the antispam configuration options are both overwhelming but also pretty limited. I couldn't find a way to allowlist certain domains for example.

**Comment by charettes** [comment]
Curious if we know the origin of the SPAM that made it through a few hours ago. Have we made any changes to the configurations lately?

**Comment by bmispelon** [comment]
> Curious if we know the origin of the SPAM that made it through a few hours ago. Have we made any changes to the configurations lately?

No configuration changes, but the timing of this latest spam wave is very suspiciously close to the deploying of d9356b48ed32d75436302e8738b03cfc08d38ccd

**Comment by charettes** [comment]
Yeah that seems to line up.

Possibly this dependency? https://github.com/django/code.djangoproject.com/commit/d9356b48ed32d75436302e8738b03cfc08d38ccd#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R9-R10

**Comment by bmispelon** [comment]
> But Trac's plugin architecture can make it a bit hard to figure out exactly what's installed and activated, so who knows?

Well what do you know, one of the sub-plugins (`tracspamfilter.filters.bayes`) was missing a dependency and was silently being skipped. That probably explains the recent wave.

See linked PR above this comment
