### ISSUE TITLE
Remove round box around main text in section "code".

### ISSUE THREAD

**Issue by jorgecarleitao** [django/code.djangoproject.com#19]
On the [code section](https://code.djangoproject.com/), the main content (left side), contains an extra bordered box.

This is pushing the text to the right, which is not consistent with the rest of the website and is removing some space to text.

**Comment by bmispelon** [comment]
Finally got around to creating a pull request for this: https://github.com/django/code.djangoproject.com/pull/40

Does that look OK? (extra instructions for a local setup can be found at https://github.com/django/djangoproject.com/issues/103#issuecomment-64092239)
