### ISSUE TITLE
There is PhoneNumberField in models in django.db

### ISSUE THREAD

**Issue by saikethan27** [django/code.djangoproject.com#196]
It is very use full to have phone number field like models.CharField and models.EmailField in model with parameters  
default_validators = [
        RegexValidator(
            regex=r'^\d{10}$',
            message=_('Phone number must be exactly 10 digits.')
        )
    ]

**Comment by bmispelon** [comment]
Hi,

This github project is for issues with the Django website itself, not with the framework. If you have feature requests for Django. please search in the list of tickets at https://code.djangoproject.com/query.

As for phone numbers, there is already a library you can install: https://github.com/stefanfoulis/django-phonenumber-field

Thanks!
