### ISSUE TITLE
Text font in section "code" different from website

### ISSUE THREAD

**Issue by jorgecarleitao** [django/code.djangoproject.com#20]
In [the main page of section "code"](https://code.djangoproject.com/), the main text has a font that seems to be different from the website.

In the chrome, the computed font in the main text is 
```
font-family: sans-serif;
```

but the computed font in the sidebar is

```
font-family: Roboto, Corbel, Avenir, 'Lucida Grande', 'Lucida Sans', sans-serif;
```

**Comment by bmispelon** [comment]
That PR should have fixed it.

Let us know if that's not the case.

Thanks!
