### ISSUE TITLE
Enable Trac timeline ticket_show_component

### ISSUE THREAD

**Issue by medmunds** [django/code.djangoproject.com#203]
Would it be possible to enable Trac's `[timeline]` [`ticket_show_component`](https://trac.edgewall.org/wiki/TracIni#timeline-ticket_show_component-option) configuration option?

This should include each ticket's "Component" in the Trac [timeline](https://code.djangoproject.com/timeline). And hopefully would add component to the timeline RSS, allowing external monitoring of tickets for particular components.

See also #202 and [forum discussion](https://forum.djangoproject.com/t/subscribe-to-trac-notifications-on-a-component/32529).

**Comment by bmispelon** [comment]
Hi again 😄 

I've created #205 and tested it locally. The way it works doesn't seem super ideal: all it does is that instead of showing the summary of a ticket, it shows `{component} - {summary}` (both in the HTML and the RSS versions). Would that still work for you?

**Comment by medmunds** [comment]
Thanks for looking into this.

Although `{component} - {summary}` isn't as helpful as a separate component RSS field, it still seems like it would add useful information to the timeline. (And I could still hack together a component watcher on top of that. Though if #202 is an actual possibility, that would be my preference.)

That's assuming the whole summary is still shown. If adding the component results in truncating the summary in HTML view, that would probably be a step backwards.

If the timeline HTML view looks reasonable to you with this enabled, I'd say let's try it out. If any regular timeline users have a strong negative reaction, we can revert it.

**Comment by bmispelon** [comment]
I've checked locally and the addition of the component doesn't trigger any extra truncation. Trac does truncate the summary to ~75 characters, but the truncation logic is done before prepending the component: https://github.com/edgewall/trac/blob/e011e2d023001fe6e17ca7bd83d30a96e6046cfa/trac/ticket/web_ui.py#L382-L385

I'm still going to attempt to fix #202, but in the meantime I'm also going to merge this as well, with the option to revert it if it's deemed to noisy.

I'll post an update here when the change is live.

**Comment by bmispelon** [comment]
(it's live, though you might have to log in to see it since the timeline is heavily cached for anonymous users)

**Comment by medmunds** [comment]
Nice, thanks. A search for `(COMPONENT_NAME -` (delimited with `(` and ` -`) finds everything for a particular component, in either the html timeline or the RSS `<title>` field.
