### ISSUE TITLE
Horizontal line in section "code" not consistent with rest of website.

### ISSUE THREAD

**Issue by jorgecarleitao** [django/code.djangoproject.com#21]
In [the main page of section "code"](https://code.djangoproject.com/), the horizontal line contains a shadow. In the rest of the website (e.g. [here](https://www.djangoproject.com/)), they don't.

**Comment by bmispelon** [comment]
I believe this was fixed with 02c8f608649f69f11a85ef041d5e665a35b7828a.

Please re-open if that's not the case.

Thanks!
