### ISSUE TITLE
Element in code/timeline hides other elements

### ISSUE THREAD

**Issue by jorgecarleitao** [django/code.djangoproject.com#22]
In [the timeline page](https://code.djangoproject.com/timeline), the element to choose the date hides other content, see image below and imagine a changeset that occupies the full line (I didn't find an example today).

![bla](https://cloud.githubusercontent.com/assets/2772607/5492176/727eab6c-86df-11e4-9667-0bd55dfb0fcb.png)

**Comment by timgraham** [comment]
This seems to be wrapping properly now.
