### ISSUE TITLE
Upgrade to Django 5.0

### ISSUE THREAD

**Issue by pauloxnet** [django/code.djangoproject.com#220]
As wrote by @bmispelon in the website repository:

> Ideally, we would also want to be running the same version of Django on both djangoproject.com and code.djangoproject.com (https://github.com/django/code.djangoproject.com).
> That's because the two sites talk to the same database (Trac uses Django's user database for authentication), and that might break if for example a newer version of Django changes the user model.

https://github.com/django/djangoproject.com/pull/1712#issuecomment-2449716352

**Comment by bmispelon** [comment]
This needs #219 to happen first (that PR is almost ready I think, I just need to work out the issues with `PYTHONWARNINGS`)

**Comment by bmispelon** [comment]
Fixed with #222

**Comment by ulgens** [comment]
Is there a plan to continue this upgrade with 5.1?

**Comment by bmispelon** [comment]
> Is there a plan to continue this upgrade with 5.1?

Absolutely! My rough plan was to give it a week or two to see if things would pop up, then proceed with the 5.1 upgrade.

If you'd like to help, opening a PR for both djangoproject.com and code.djangoproject.com would be appreciated. Also running the test suite with warnings on to see if we might get bitten y some changes.

Thanks! 🎸
