### ISSUE TITLE
SplitDateTimeWidget crashes while processing initials

### ISSUE THREAD

**Issue by nstonic** [django/code.djangoproject.com#229]
I have a model with DateTime field. I want to set initials for this field in django admin by query params. For ex
`http://127.0.0.1:8000/admin/app/model/add/?created_at=2024-10-10%2005%3A57%3A31`

Admin sites crashes with 500 error. This happens because SplitDateTimeWidget expects an object of datetime type, but it is passed the string instead.

Proposed fix

```py
    def decompress(self, value):
        if isinstance(value, str):
            try:
                value = datetime.fromisoformat(value)
            except ValueError:
                return [None, None]
        if value:
            value = to_current_timezone(value)
            return [value.date(), value.time()]
        return [None, None]
```

**Comment by bmispelon** [comment]
Hi,

This bug tracker is for Django's website itself, not for Django. Check the FAQ for places where you can get help with your question: https://docs.djangoproject.com/en/5.1/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help
