### ISSUE TITLE
Style issues in wiki

### ISSUE THREAD

**Issue by berkerpeksag** [django/code.djangoproject.com#23]
![screenshot from 2014-12-19 06 55 57](https://cloud.githubusercontent.com/assets/26338/5500387/21715ab8-874c-11e4-97e7-85f204cf0cb4.png)

See https://code.djangoproject.com/wiki/DjangoFellows/BerkerPeksag for the actual page.

**Comment by bmispelon** [comment]
I believe this has been fixed:
![tracstylingissues_ _django_-_2015-04-26_10 29 12](https://cloud.githubusercontent.com/assets/6345/7336452/86b4a656-ebff-11e4-821d-a41fc515951c.png)

Please re-open if that's not the case.

Thanks!

**Comment by berkerpeksag** [comment]
Yes, looks great. Thanks!
