### ISSUE TITLE
Inline buttons have global styling

### ISSUE THREAD

**Issue by MarkusH** [django/code.djangoproject.com#26]
![trac1](https://cloud.githubusercontent.com/assets/475613/5518353/8f4c82f0-8923-11e4-96e8-ced103b85b5c.png)

**Comment by bmispelon** [comment]
What would you suggest instead? A link, a smaller button, ...?

Danke!

**Comment by bmispelon** [comment]
What about using the same style as the new inline buttons introduced in 44525877404e251f5cae4b06c2bf32e238f6c9cf?
