### ISSUE TITLE
Quotation in ticket comment can hide comment action buttons

### ISSUE THREAD

**Issue by shaib** [django/code.djangoproject.com#27]
See https://code.djangoproject.com/ticket/24096#comment:6
issue #22 may be related.
(couldn't get the image to upload for some reason... this one is from a different ticket, url updated)

**Comment by shaib** [comment]
![django-trac-comments-bug](https://cloud.githubusercontent.com/assets/129187/5695452/fb4fab28-99ac-11e4-81c5-84360e9e7732.png)

**Comment by bmispelon** [comment]
It seems that since 44525877404e251f5cae4b06c2bf32e238f6c9cf, the buttons are now fully hidden.

Progress? :)

**Comment by shaib** [comment]
:smile: :cry:

**Comment by bmispelon** [comment]
@shaib I added a `z-index` to the buttons so that they now show on top. Is that better (see screenshot in above pull request)?

**Comment by bmispelon** [comment]
The PR is here (I though github would autolink but it appears not): https://github.com/django/code.djangoproject.com/pull/47

I've stumbled upon a configuration where the text from the quote flows around the buttons so that might be a winner.

**Comment by shaib** [comment]
Thanks @bmispelon  :+1:  :cake:
