### ISSUE TITLE
No access to Wiki page history

### ISSUE THREAD

**Issue by shaib** [django/code.djangoproject.com#28]
I was trying to see the list of previous versions of the page https://code.djangoproject.com/wiki/CommitterTips but there is no link to this list anywhere on the page. The only way I could follow its history was to use the highly non-obvious "last modified" link to get to the diff of the last change, and proceed from there by manually editing the version number in the URL.

**Comment by timgraham** [comment]
Found this from trachacks.scss:
```
div[role="main"] #ctxtnav {
    display: none;
}
```
