### ISSUE TITLE
Trac GitHub login error: MissingTokenError

### ISSUE THREAD

**Issue by jdufresne** [django/code.djangoproject.com#31]
Originally reported [here](https://code.djangoproject.com/ticket/24216)

I am using Firefox 35 on Fedora 20.

Every time I log in by clicking "GitHub Login" near the top of all `code.djangoproject.com` pages Trac reports an internal error and I am presented with the error page attached. If I navigate away from this error page I am actually logged in, so this error doesn't stop me from using the site as a logged in user. You can see in the screenshot it says "logged in as jdufresne".

I do use various Firefox add-ons, so perhaps that may be an issue? Beyond typical web developer add-ons, my add-ons can manipulate cookies and HTTP referer. I do have cookies enabled for `.djangoproject.com` and `.github.com` so I don't think that is it.

I have reproduced this on multiple boxes that share the same Firefox profile and OS.

![internal-error-django](https://cloud.githubusercontent.com/assets/347634/5905440/f929dfbe-a544-11e4-8ce4-57c8989469be.png)

**Comment by timgraham** [comment]
Is it still an issue? Absent some way to reproduce it ourselves, not sure there's much value in leaving the ticket open.

**Comment by jdufresne** [comment]
I think this is related to some Firefox add-on I am using. This does not happen when using a fresh Firefox profile. My best guess is that it is related to the [Cookie Monster add-on](https://addons.mozilla.org/en-us/firefox/addon/cookie-monster/). Currently I workaround this issue by using "DjangoProject Login" which works for me.

**Comment by jdufresne** [comment]
Sorry for the back-to-back posts.

Actually, this look like it might be related to the [smart referer](https://addons.mozilla.org/en-us/firefox/addon/smart-referer/) add-on. Does GitHub login require a `Referer` header to work properly?

I can whitelist this site so it will continue in the future.

If working without a Referer is important, feel free to re-open, but I can workaround this easy enough.
