### ISSUE TITLE
Improve UX of ticket flags with an explanation of next steps

### ISSUE THREAD

**Issue by timgraham** [django/code.djangoproject.com#33]
The idea is to add something to [tickethacks.js](https://github.com/django/code.djangoproject.com/blob/master/trac-env/htdocs/tickethacks.js) which translates the "Has patch", "Needs documentation", etc. flags to a prominently displayed paragraph that explains how to move the ticket forward.

For example, "Has patch=Yes" and the rest "no" would say, "To move this ticket forward, a community member needs to review the patch using the [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) and either mark the ticket as "Ready for checkin" if everything looks good, or leave comments for improvement and mark the ticket as "Patch needs improvement".

I'll be happy to provide further guidance on this for anyone interested in tackling the implementation.

**Comment by collinanderson** [comment]
Sweet.

**Comment by olasitarska** [comment]
That would be amaaazing. :clap:

**Comment by prestontimmons** [comment]
@timgraham I wouldn't mind working on this. Do you think the status would appear near the top of the ticket page?

**Comment by MarkusH** [comment]
:+1:

**Comment by timgraham** [comment]
Yes, I was thinking between the flags and the description.

**Comment by timgraham** [comment]
PR: https://github.com/django/code.djangoproject.com/pull/76
