### ISSUE TITLE
active (current) page in menu is not highlighted

### ISSUE THREAD

**Issue by wimfeijen** [django/code.djangoproject.com#35]
Hi,

I like the new layout very much. 

A small improvement could be to highlight the current page in the top menu. 

For example, we could use light green as a color for the active page if we are on that page or a subpage. If we want the effect to differ from the mouse-over effect, we could add an underline to the mouse-over.

It is a small detail that helps people figuring out where they are.

**Comment by timgraham** [comment]
Should go to the django/djangoproject.com/ issue tracker (this repository is for Trac configuration).
