### ISSUE TITLE
Does code.djangoproject.com really support mobile dislpay?

### ISSUE THREAD

**Issue by mishavetl** [django/code.djangoproject.com#37]
Is code.djangoproject.com responsive?

![screenshot_2015-03-31-08-30-20](https://cloud.githubusercontent.com/assets/9119326/6912871/91514af8-d780-11e4-9bb8-c22bdce1a9ea.png)

**Comment by bmispelon** [comment]
Hi,

We've copied over the CSS from `djangoproject.com` whish **is** responsive but it's possible that trac's CSS is interfering with that.

If you have improvements to suggest, please open issues (or better yet, pull requests) to https://github.com/django/djangoproject.com/issues (that's where we track all issues).

Thanks!
