### ISSUE TITLE
Solution for design problems on mobile phones

### ISSUE THREAD

**Issue by mishavetl** [django/code.djangoproject.com#38]
I have a solution for design problems on mobile phones. You need to add 
`<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=1.0, minimum-scale=1.0, maximum-scale=1.0">`
to a head tag of your base site.

**Comment by bmispelon** [comment]
Hi,

Do you have a reference for this change or an explanation of what it doe?
Ideally some before/after screenshots would also really help.

Thanks!

**Comment by mishavetl** [comment]
Hello,

This code sets width to device width, so website content would be responsive.

**Comment by timgraham** [comment]
I guess a mobile design should probably be addressed upstream in Trac itself: http://trac.edgewall.org/ticket/11953
