### ISSUE TITLE
Trac doesn't show "logged in as xxx" anymore

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#51]
After logging in with github, the navigation looks like this:
![custom_query_ _django_-_2015-05-01_13 03 31](https://cloud.githubusercontent.com/assets/6345/7429509/8b62ac46-f002-11e4-85a2-c7d7dbc8906c.png)

It used to say "logged in as xxx" and the "DjangoProject login" link was not there.

Maybe that's related to the recent Trac update?

**Comment by aaugustin** [comment]
The code that handles this is here:

https://github.com/trac-hacks/trac-github/blob/master/tracext/github.py#L24-L34

and the configuration is there:

https://github.com/django/code.djangoproject.com/blob/master/trac-env/conf/trac.ini#L79-L82

Perhaps `login.label = DjangoProject Login` causes this issue.
