### ISSUE TITLE
Mark a ticket with multiple versions?

### ISSUE THREAD

**Issue by jmfederico** [django/code.djangoproject.com#52]
Hello

I'm new to django and the community, if this ticket is opened in the wrong place, please point me to the right one. Thanks in advance.

I just started browsing the tickets in https://code.djangoproject.com and noticed that it is not possible to mark an item as valid for more than one version of django.

I also found that when a ticket applies to more than 1 version, it is marked as the lowest version it applies to.

Don't know if this has been discussed before, but I think it would be useful to have the ability to mark a ticket as valid for more than one version, this would so that when a search is performed, all the relevant tickets for the version you are looking for show up.

I for instance am using version 1.8.1 already, but found one of the [tickets](https://code.djangoproject.com/ticket/24715) that was marked as 1.7, even though it also applies to 1.8 and master. Would have saved me some time if it was marked 1.8.

Cheers

**Comment by bmispelon** [comment]
Hi,

We use [Trac](http://trac.edgewall.org/) as a ticket tracker and I don't believe it can be configured to be used the way you describe.
This means that the feature would have to be added directly to Trac and we don't have control over that.

Therefore I'm closing this. If you're interested in pursuing this issue further, the next step would be to open a feature request to Trac directly (or if there's a way to configure our Trac, please point us to the documentation or submit a pull request).

Thanks!
