### ISSUE TITLE
Blockquotes are double-wrapped

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#57]
When using a quote in a ticket's description:

    Doing something
    > Like this for example

It results in the quote being doubly outlined, like so (see https://code.djangoproject.com/ticket/25166#ticket for a live example):
![25166_ incorrect_statement_in_custom_model_permission_documentation _ _django_-_2015-07-23_00 00 57](https://cloud.githubusercontent.com/assets/6345/8838585/e96d080c-30cd-11e5-844b-47e1b4d6c878.png)

**Comment by timgraham** [comment]
Looks like you had two spaces after the '>'.
