### ISSUE TITLE
"WIKI_VIEW privileges are required to perform this operation."

### ISSUE THREAD

**Issue by zborboa-google** [django/code.djangoproject.com#58]
I tried to use the Github login and the DjangoProject login. Both resulted in the error:
"Error: Forbidden
WIKI_VIEW privileges are required to perform this operation. You don't have the required permissions."

![screenshot](https://cloud.githubusercontent.com/assets/6154360/9611980/d7fc7870-5097-11e5-9d95-32cb5930ad20.png)

**Comment by timgraham** [comment]
Could you ping me (timograham) on IRC to help debug this?

**Comment by timgraham** [comment]
I just upgrade Trac to 1.0.8. The previous version had a bug: "the session for an authenticated username containing non-alphanumeric characters could not be retrieved, resulting in the user being denied access to every realm and resource." I wonder if this affected you?

**Comment by zborboa-google** [comment]
@timgraham - That seemed to fix it. I can now view the tickets. Thank you
