### ISSUE TITLE
The 'logout' button is ineffective

### ISSUE THREAD

**Issue by jribbens** [django/code.djangoproject.com#61]
Clicking 'logout' is ineffective - if you click 'DjangoProject Login' afterwards then you are logged straight back in again without being asked for any username or password.

I am using Chrome 46.0.2490.86m (64-bit) on Windows.

**Comment by timgraham** [comment]
Do you know if browsers cache HTTP auth credentials? e.g. https://code.google.com/p/chromium/issues/detail?id=108291 Not sure it's something we can fix or not.

**Comment by bmispelon** [comment]
From what I understand, trac uses basic http auth which is not designed ti support the "logout" feature: http://stackoverflow.com/a/233551/257654

**Comment by jribbens** [comment]
It does use HTTP basic auth, yes. So perhaps the logout button just needs to be removed, since it can't work. Obviously, making people believe they have logged out when they actually haven't is somewhat suboptimal.

**Comment by felixxm** [comment]
Fixed in eb16ed0b13ec81d1c798599683ea7fba391c2053.
