### ISSUE TITLE
Login with github is secret

### ISSUE THREAD

**Issue by amosonn** [django/code.djangoproject.com#62]
I found out this option on https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/
In other contexts, the login displays a popup with username and password, and no clear way to login using github.

**Comment by timgraham** [comment]
There should be "GitHub Login" to the left of "DjangoProject Login" on all Trac pages (e.g. https://code.djangoproject.com/).

**Comment by bmispelon** [comment]
Here's what the page looks like for me. As Tim said, there should be a "GitHub Login" link at the top:
![django_-_2015-12-09_17 06 53](https://cloud.githubusercontent.com/assets/6345/11690528/56980314-9e97-11e5-92e6-613868f0bb31.png)

**Comment by amosonn** [comment]
Shame on me for not looking harder.
However, this one (logged in version of addticket) doesn't have the button.
As far as I can tell, other github-logged-in versions don't have it as
well. Maybe intended, but it is somewhat confusing - if you have some tabs
opened while you were logged in, and another one says you're not, you might
not find it. The "you might want to <a href=/login>do so</a> now", which
doesn't suggest the github option, is also confusing.

**Comment by amosonn** [comment]
Shame on me for not looking harder.
However, this one (logged in version of addticket) doesn't have the button.
As far as I can tell, other github-logged-in versions don't have it as
well. Maybe intended, but it is somewhat confusing - if you have some tabs
opened while you were logged in, and another one says you're not, you might
not find it. The "you might want to <a href=/login>do so</a> now", which
doesn't suggest the github option, is also confusing.

![django2](https://cloud.githubusercontent.com/assets/3142573/11691536/163893da-9ea4-11e5-8446-c62e2f37bcc6.png)

**Comment by bmispelon** [comment]
I agree that it's confusing. It's actually a bug that appeared a while ago and we haven't been able to fix it yet: #51.

Thanks.
