### ISSUE TITLE
Update versions on wiki start page 

### ISSUE THREAD

**Issue by alasdairnicol** [django/code.djangoproject.com#63]
The information on https://code.djangoproject.com/wiki#Djangoreleaseprocess is out of date. Please could somebody with WIKI_ADMIN privileges update it?

 * 1.9 is the current stable branch
 * 1.8 is now the LTS branch, not LTS and stable. Note typo of repeated 'branch branch' as well.
 * 1.7 is no longer supported.

Perhaps it would be better for this wiki page to link to somewhere else, e.g. https://www.djangoproject.com/download/#supported-versions, so that it doesn't need to be updated for each release.

**Comment by timgraham** [comment]
Done in https://code.djangoproject.com/wiki/WikiStart?action=diff&version=301, thanks!
