### ISSUE TITLE
Add new ticket type - "Docs"

### ISSUE THREAD

**Issue by arogachev** [django/code.djangoproject.com#68]
I think it's quite common type of problems for any framework / program. Can't find it, the only remaining option is to use broad "Uncategorized".

**Comment by timgraham** [comment]
I guess you didn't see "Documentation" under "Component".

**Comment by arogachev** [comment]
@timgraham Sorry, I didn't see it in components. So is it correct to use "Uncategorized" type for this kind of tickets? Another problem is I can't combine `contrib.admin` with `Documentation`. How you advise to fill ticket info in this case?

**Comment by timgraham** [comment]
We use the Documentation component regardless of what part of Django the documentation applies to.
