### ISSUE TITLE
Round time difference to hours, etc.

### ISSUE THREAD

**Issue by arogachev** [django/code.djangoproject.com#70]
In ticket change history I saw time difference displayed like "Opened 109 minutes ago". I think the better practice is to round it to hours, for example "Opened 2 hours ago". I see it used on many sites and in my opinion it's more human readable and friendly.

**Comment by timgraham** [comment]
Unless there's some way to customize that (I didn't look as I don't think it really matters), this feature request would have to go to our bug tracker, [Trac](https://trac.edgewall.org/).

**Comment by arogachev** [comment]
@timgraham OK. but issues are locked in [Github trac repo](https://github.com/edgewall/trac). Where to add it in this case?

**Comment by timgraham** [comment]
There's a "New Ticket" link if you follow the link in my comment.
