### ISSUE TITLE
Move changes table to left on ticket detail page

### ISSUE THREAD

**Issue by berkerpeksag** [django/code.djangoproject.com#71]
I was able to move it back to its original location in a quick devtools session:

![screenshot from 2016-09-26 01 45 16](https://cloud.githubusercontent.com/assets/26338/18818760/143bce4a-838b-11e6-8d53-3823d22f7248.png)

I can probably add this quick modification to `scss/trachacks.scss`.

**Comment by timgraham** [comment]
Maybe we would get used to the change on time, but I'm in favor. Especially on ticket changes without comments, it seems odd to have a big whitespace on the left. 

It might be nice to give feedback to the Trac developers to see if they really want to keep that change.

**Comment by claudep** [comment]
+1 from me

**Comment by claudep** [comment]
Also having the comment cutting a comment like the image below is terrible!
![trac-comment](https://cloud.githubusercontent.com/assets/143192/18886381/eb66a97a-84ef-11e6-9994-879c24f465e5.png)
