### ISSUE TITLE
"core developer" badge not working anymore

### ISSUE THREAD

**Issue by bmispelon** [django/code.djangoproject.com#74]
There used to be a "core developer" badge in the comments of tickets but it seems to have disapeared.

It seems it might have been caused by Trac's update where it now shows the user's full name ("Baptiste Mispelon") instead of their GitHub username ("bmispelon") like it did before.

The javascript hack that added the badge relied on being able to extract the username and therefore doesn't work anymore.

**Comment by timgraham** [comment]
Do you feel it's important to restore? Not that everyone knows the core developers by name, but it's probably easier to recognize them by full name rather than username. I think Trac has a toggle to disable the display of full names but I don't think going back to usernames would be an improvement.

**Comment by manfre** [comment]
One observation, neither for or against is that the core dev tag was
applied to all comments made by the user, even those before they became a
core dev.

The tag adds an extra implied weight to the comments, which sometimes
shifts the interpretation/flow of long lived tickets.

**Comment by aaugustin** [comment]
If we don't provide an easy way to identify committers, now that there are several dozen, we'll have to remove the "don't reopen a ticket closed by a core dev" rule.

**Comment by timgraham** [comment]
I've submitted a doc proposal to clarify that anyone can close ticktes as wontfix and that discussion should happen on the mailing list for all such tickets: https://github.com/django/django/pull/7619.
