### ISSUE TITLE
Logout nav item style

### ISSUE THREAD

**Issue by matsaman** [django/code.djangoproject.com#77]
Has some imperfect styling that increases the entire nav area's height, this'll fix it:

    li form.trac-logout { display: inline-block !important; }
    li form.trac-logout button {
    	height: auto;
    }

**Comment by timgraham** [comment]
Adding `height: auto;` seems sufficient to me, did I miss the reason for the first line?

**Comment by matsaman** [comment]
Technically, visually just the second rule might suffice, but if you add, for example, `* { outline: 1px solid fuchsia; }`, you'll see the use of the first rule.

**Comment by timgraham** [comment]
Great, thanks for the explanation.
