### ISSUE TITLE
Captcha error page is missing "Send" button

### ISSUE THREAD

**Issue by m-aciek** [django/code.djangoproject.com#78]
Recaptcha module does not include "Send" button. Experienced on Firefox.
![zrzut ekranu z 2016-11-02 22-14-42](https://cloud.githubusercontent.com/assets/9288014/19947800/0ef45916-a14a-11e6-9be3-e9851169b7f3.png)

**Comment by timgraham** [comment]
I don't know, other people are submitting captchas and I haven't seen other reports of this. Can you try fiddling with the CSS to suggest a fix?

**Comment by m-aciek** [comment]
Sure, I will try to investigate.

**Comment by adamchainz** [comment]
Had the same thing just now:

<img width="787" alt="screen shot 2017-06-03 at 19 23 35" src="https://cloud.githubusercontent.com/assets/857609/26756050/458faf08-4892-11e7-9d5b-81f8f1614edb.png">

**Comment by adamchainz** [comment]
After looking at the CSS I can't see any rules applying to the widget that don't come from the recaptcha code itself. But then googling I found this is recaptcha 1 which is no longer supported and can't be promised to keep functioning: https://developers.google.com/recaptcha/docs/faq . We should upgrade to recaptcha 2.

**Comment by adamchainz** [comment]
N.B. for anyone wanting to have a look, you can visit https://code.djangoproject.com/captcha directly without having to submit a comment that looks like spam.

**Comment by timgraham** [comment]
The latest version of reCaptcha uses a check box, so I think this is obsolete.
