### ISSUE TITLE
ReCAPTCHA is Still Broken

### ISSUE THREAD

**Issue by Miserlou** [django/code.djangoproject.com#82]
Upgrading to v2 didn't seem to work yet, in fact - it's so broken that I can't comment on the ticket on the Trac!

Here's the SS: 
<img width="1474" alt="screen shot 2018-02-02 at 10 18 42 am" src="https://user-images.githubusercontent.com/139987/35740356-8b3a580c-0802-11e8-9c2c-ede1dc88301d.png">

**Comment by Miserlou** [comment]
Also, the content of the comment which it has at 93% chance of spam was:

`Great! Let's see if this works..`

**Comment by timgraham** [comment]
Did you complete a captcha before seenig that? The fact that seemingly valid submissions are often marked as spam is a separate issue (e.g. #67).

**Comment by Miserlou** [comment]
No, I was never presented with a CAPTCHA at all after I got the comment on the ticket.

**Comment by timgraham** [comment]
I disabled captchas.
