### ISSUE TITLE
Allow only moderators to re-assign an already assigned bug

### ISSUE THREAD

**Issue by CuriousLearner** [django/code.djangoproject.com#91]
I've seen instances where one person took over the bug and re-assigned to themselves, which was already being actively worked on.

It is good to restrict these privileges only to moderators (or at least to people who are used to bug-trackers and have already contributed). That would make FOSS more sustainable as we were discussing in DjangoCon US Sprints.

**Comment by timgraham** [comment]
In my experience, it's more common that someone assigns themselves a bug and then never completes it. I think the status quo is okay.

**Comment by CuriousLearner** [comment]
Yeah, but in that case, the other person can ask on the bug first if the already assigned person is already working. In case of no replies (which would be the case most of the time), the other person can continue working on the bug say after 2-3 days of waiting for the reply. 

Does it sound feasible? Because anyone taking over a bug which is already actively being worked upon doesn't look good. Most of the other bug trackers already account for these instances.

**Comment by timgraham** [comment]
It's not a big problem that I've seen, and I think it would add more friction for the more common case.

I don't know if Trac offers the feature.

**Comment by claudep** [comment]
Agreed with Tim, I didn't see that problem happening many times, and resolving this technically where it can be solved by people interacting politely seems a bit overkill for that case. We can always reconsider if we see that issue becoming more problematic in the future.
